# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://www.taoga.fr/"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: "/"

# Title of the Site
title: Tao Ga Paris Kung Fu
# Description of the Site
description: Originaire du sud de la chine, ce style de Kung Fu est adapté pour ceux qui recherche du self défense comme un style traditionnel Chinois à Paris France
# URL of Image of the Site
site-image: /assets/images/logo.jpg
# Keywords of the Site
site-keywords: Kung-Fu, Paris, Jardin du luxembourg, Self-Defense, Combat, boxe, Wushu, Art martial Chinois, Arts martiaux, shaolin, Andrew Lum, Lum Tai Yung, Leslie Mow
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/wide_leslie_frontpage.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: taogafrance@gmail.com
linktree: https://linktr.ee/taogakungfu
facebook_group: groups/TaoGa/
facebook_username: 100080408923212
twitter_username:
instagram_username: "tao_ga_kung_fu_paris" 
linkedin_username: 
github_username: 
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 


# Name of the Author
author-name: Leslie Mow
# URL for the Image of the Author
author-image: /assets/images/leslie.jpg
history: "
Le Kung-Fu \"TAO GA\" est une variante intéressante de la discipline \"Sil Lum Fut GA Kuen\", enseignée par la Gee Yung Chinese Physical Culture Association à Hawaii.<br><br>

Ce style a été amené de Chine par le Grand Maître <b>Lum Tai Yung</b> et transmise à Maître Andrew Lum au sein de l'Académie des Arts Martiaux Chinois d'Hawaï.<br><br>

Le système Tao Ga du Kung-Fu se concentre sur deux aspects principaux : <b>la vitesse d'attaque</b> et <b>le contrôle de l'adversaire</b>.<br><br>

La rapidité est obtenue grâce à une relaxation profonde et à l'absence de contraction musculaire, permettant des coups rapides et puissants.<br><br>

Le contrôle de l'adversaire est également essentiel. Il repose sur une observation attentive des mouvements de l'opposant, permettant d'anticiper ses attaques ou de riposter efficacement. Ce contrôle peut se manifester de diverses manières.<br><br>

Par exemple, bloquer une attaque offre une courte opportunité pour frapper et provoquer une réaction prévisible chez l'adversaire. En anticipant la prochaine attaque, il devient possible de contre-attaquer de manière imprévisible.<br><br>

Frapper l'adversaire le force à réagir, à se tourner ou à se baisser, ouvrant ainsi de nouvelles opportunités pour le pratiquant.<br><br>

<b>Leslie Mow</b>, est un pratiquant d'arts martiaux accompli. Il a eu l'honneur d'apprendre directement auprès de Maître Andrew Lum. De plus, Leslie Mow a eu la chance de pratiquer le Tai Chi Yang à un niveau avancé avec le Grand Maître Tung Hu Ling pendant 40 ans.<br><br>

Cette approche dynamique et stratégique fait du Tao Ga une discipline enrichissante, où chaque mouvement est un équilibre entre rapidité et précision.


"
  
# 60 Words About the Author
author-about: "
<b>Leslie Mow</b> est un maître accompli qui a appris l'art du Tao Ga auprès de <b>Maître Andrew Lum</b> pendant plus de 45 ans à Hawaii, l'endroit où il est né.<br><br>

Il a également eu l'opportunité d'étudier le Tai Chi Yang auprès du <b>Grand Maître Tung Hu Ling</b> pendant de nombreuses années, ce qui fait de lui un maître avisé et très complet.<br><br>

<b>Leslie Mow</b> enseigne non seulement les techniques de combat à mains nues, mais aussi l'utilisation d'armes telles que la <b>canne courbe, le bâton court et mi-long</b>.<br><br>

Son approche, fondée sur une observation attentive et une relaxation profonde, permet d'anticiper les mouvements de l'adversaire et de riposter efficacement. Cette maîtrise fait de lui un pratiquant respecté et un enseignant précieux dans le domaine des arts martiaux.
"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linktr.ee/taogakungfu

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - plugins/no_date

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
